apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-l7b5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-l7b5@sha256:e06ee00a89487e9fb0a9cb28663db3fc6ae1fa9b066a7c9b0fd3997c9c9a3fd7
        name: my-nodejs
        resources: {}
status: {}
